### ISSUE TITLE
Timeline is not re-rendered after adding a new event to timelineData model

### ISSUE THREAD

**Issue by qsmpro** [fmaturel/angular-timelinejs3#4]
When a new event is dynamically added to $scope.timelineData nothing happens since the data watch in the timeline directive does not check for model equality. When there is a third parameter of this function set to true it fixes the issue, however, this solution could lead to performance issues.

**Comment by fmaturel** [comment]
Yes you're right, angular does not check the nested object properties as soon as the object reference is still the same. Angular documenation states that :

> When` objectEquality == true, inequality of the watchExpression is determined according to the angular.equals function. To save the value of the object for later comparison, the angular.copy function is used. This therefore means that watching complex objects will have adverse memory and performance implications.

For performance reasons, i'd prefer not using this option (my project has big timelines).

To solve your problem, you could create a copy of your object, update it with new data, and replace your timelineData with it (so that object reference is changed). Or you may fork the project and add the 'true' argument to the `watch` ;)

Thanks for the suggestion anyway.

**Comment by anurag6792** [comment]
When the new event is added , the event is added on the timeline but media(video) is not rendered.Can you suggest something?
